"""Build the sealed classic-runtime compatibility capsule.

The browser never loads the historical scripts individually.  Their readable source
is retained under ``motorcad_studio/frontend_legacy`` and compiled into one ES-module
payload consumed by ``static/core/legacy-runtime.js``.  This preserves current HMI
behaviour while eliminating load-order drift and uncontrolled ``window`` exports.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = PACKAGE_ROOT / "frontend_legacy"
STATIC_CORE = PACKAGE_ROOT / "static" / "core"
SOURCE_CATALOG_PATH = SOURCE_ROOT / "runtime-catalog.json"
OUTPUT_CATALOG_PATH = STATIC_CORE / "classic-runtime.catalog.json"
OUTPUT_SOURCE_PATH = STATIC_CORE / "classic-runtime-source.js"


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _load_paths() -> list[str]:
    payload = json.loads(SOURCE_CATALOG_PATH.read_text(encoding="utf-8"))
    paths = payload.get("sources") if isinstance(payload, dict) else None
    if not isinstance(paths, list) or not paths:
        raise RuntimeError("frontend legacy runtime catalog is missing sources")
    normalized: list[str] = []
    for raw in paths:
        value = str(raw or "").strip()
        if not value.startswith("/static/") or not value.endswith(".js"):
            raise RuntimeError(f"invalid legacy runtime path: {value!r}")
        if value in normalized:
            raise RuntimeError(f"duplicate legacy runtime path: {value}")
        normalized.append(value)
    if normalized[0] != "/static/release-manifest.js":
        raise RuntimeError("release-manifest.js must be the first legacy source")
    if normalized[-1] != "/static/module-registry.js":
        raise RuntimeError("module-registry.js must be the final legacy source")
    return normalized


def _source_file(runtime_path: str) -> Path:
    relative = runtime_path.removeprefix("/static/")
    candidate = (SOURCE_ROOT / relative).resolve()
    root = SOURCE_ROOT.resolve()
    if candidate != root and root not in candidate.parents:
        raise RuntimeError(f"legacy source escapes root: {runtime_path}")
    return candidate


def build_payload() -> tuple[dict[str, Any], str]:
    paths = _load_paths()
    sections: list[str] = []
    file_rows: list[dict[str, Any]] = []
    for runtime_path in paths:
        path = _source_file(runtime_path)
        if not path.is_file():
            raise RuntimeError(f"legacy runtime source is missing: {runtime_path}")
        raw = path.read_bytes()
        text = raw.decode("utf-8")
        file_rows.append({
            "runtime_path": runtime_path,
            "source_path": str(path.relative_to(PACKAGE_ROOT)).replace("\\", "/"),
            "size_bytes": len(raw),
            "sha256": _sha256_bytes(raw),
        })
        sections.append(
            "\n;__MCS_LEGACY_OWNER__(" + json.dumps(runtime_path, ensure_ascii=False) + ");\n"
            + f"/* ===== BEGIN {runtime_path} ===== */\n"
            + text
            + f"\n/* ===== END {runtime_path} ===== */\n;\n"
        )
    source = "".join(sections)
    source_bytes = source.encode("utf-8")
    catalog: dict[str, Any] = {
        "authority": "MotorCADStudioClassicRuntimeCatalogV1",
        "format_version": 1,
        "source_count": len(paths),
        "first_source": paths[0],
        "last_source": paths[-1],
        "source_size_bytes": len(source_bytes),
        "source_sha256": _sha256_bytes(source_bytes),
        "sources": file_rows,
    }
    return catalog, source


def render_outputs() -> tuple[str, str]:
    catalog, source = build_payload()
    catalog_text = json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=False) + "\n"
    source_literal = json.dumps(source, ensure_ascii=False)
    module_text = (
        "/* Generated sealed classic-runtime source. Do not edit this file directly. */\n"
        f"export const CLASSIC_RUNTIME_CATALOG = Object.freeze({json.dumps(catalog, ensure_ascii=False, separators=(',', ':'))});\n"
        f"export const CLASSIC_RUNTIME_SOURCE = {source_literal};\n"
    )
    return catalog_text, module_text


def build(*, check: bool = False) -> dict[str, Any]:
    catalog_text, source_text = render_outputs()
    expected = {
        OUTPUT_CATALOG_PATH: catalog_text,
        OUTPUT_SOURCE_PATH: source_text,
    }
    changed: list[str] = []
    issues: list[dict[str, str]] = []
    for path, content in expected.items():
        actual = path.read_text(encoding="utf-8") if path.is_file() else None
        if actual == content:
            continue
        if check:
            issues.append({
                "code": "CLASSIC_RUNTIME_CAPSULE_OUT_OF_SYNC",
                "path": str(path),
                "detail": "run python -m motorcad_studio.tools.build_frontend_capsule --write",
            })
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        changed.append(str(path.relative_to(PACKAGE_ROOT.parent)).replace("\\", "/"))
    catalog = json.loads(catalog_text)
    return {
        "authority": "MotorCADStudioClassicRuntimeBuildV1",
        "compatible": not issues,
        "mode": "check" if check else "write",
        "source_count": catalog["source_count"],
        "source_size_bytes": catalog["source_size_bytes"],
        "source_sha256": catalog["source_sha256"],
        "changed": changed,
        "issues": issues,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true")
    group.add_argument("--write", action="store_true")
    args = parser.parse_args()
    report = build(check=args.check)
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report["compatible"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
