"""Shared dependency and runtime-state context for migrated HTTP operations."""
from __future__ import annotations
import threading
from typing import Any
from ...bootstrap.container import ServiceContainer

class HttpOperationContext:

    def __init__(self, container: ServiceContainer):
        self.settings = container.settings
        self.static_dir = container.static_dir
        self.distribution_manifest_path = container.distribution_manifest_path
        self.module_registry = container.module_registry
        self.db = container.db
        self.logs = container.logs
        self.registry = container.registry
        self.motor_plugins = container.motor_plugins
        self.templates = container.templates
        self.installations = container.installations
        self.automation_registry = container.automation_registry
        self.calibration = container.calibration
        self.native_closure_profiles = container.native_closure_profiles
        self.native_closure_registry = container.native_closure_registry
        self.native_parity_profiles = container.native_parity_profiles
        self.native_parity = container.native_parity
        self.sessions = container.sessions
        self.tasks = container.tasks
        self.runtime_lifecycle_qualification = container.runtime_lifecycle_qualification
        self.runtime_contract = container.runtime_contract
        self.motor_domain = container.motor_domain
        self.motorcad_binding_planner = container.motorcad_binding_planner
        self.native_semantic_binding_authority = container.native_semantic_binding_authority
        self.workspace = container.workspace
        self.domain = container.domain
        self.solution_repository = container.solution_repository
        self.solutions = container.solutions
        self.design_starters = container.design_starters
        self.engineering_lineage = container.engineering_lineage
        self.execution_planning = container.execution_planning
        self.optimization_planning = container.optimization_planning
        self.engineering_platform = container.engineering_platform
        self.analysis_workspace_service = container.analysis_workspace_service
        self.analysis_guidance = container.analysis_guidance
        self.analysis_application = container.analysis_application
        self.standard_validation = container.standard_validation
        self.standard_validation_jobs = container.standard_validation_jobs
        self.data_factory = container.data_factory
        self.monitoring = container.monitoring
        self.material_catalog = container.material_catalog
        self.material_library = container.material_library
        self.result_viewer = container.result_viewer
        self.result_aggregates = container.result_aggregates
        self.result_sets = container.result_sets
        self.engineering_requirements = container.engineering_requirements
        self.result_interpretation = container.result_interpretation
        self.engineering_scorecard = container.engineering_scorecard
        self.optimization_result_authority = container.optimization_result_authority
        self.results_optimization = container.results_optimization
        self.optimization_guidance = container.optimization_guidance
        self.qualification_campaigns = container.qualification_campaigns
        self.manufacturing_robustness = container.manufacturing_robustness
        self.active_learning = container.active_learning
        self.engineer_journey = container.engineer_journey
        self.workstation_acceptance = container.workstation_acceptance
        self.windows_production_qualification = container.windows_production_qualification
        self.windows_golden_journey_qualification = container.windows_golden_journey_qualification
        self.production_soak_qualification = container.production_soak_qualification
        self.ui_soak_qualification = container.ui_soak_qualification
        self.release_candidate_gate = container.release_candidate_gate
        self.production_hardening_runtime = container.production_hardening_runtime
        self.candidate_validation = container.candidate_validation
        self.reproducibility_environment = container.reproducibility_environment
        self.optimization_evidence_ledger = container.optimization_evidence_ledger
        self.model_workbench = container.model_workbench
        self.ui_guidance = container.ui_guidance
        self.engineering_workflow = container.engineering_workflow
        self.release_service = container.release_service
        self.system_service = container.system_service
        self._runtime_gate = container.runtime_gate
        self._invalidate_runtime_gate = self.system_service.invalidate_runtime_gate
        self._ensure_motorcad_runtime_ready = self.system_service.ensure_runtime_ready
        self._ensure_motorcad_submission_ready = self.system_service.ensure_submission_ready
        self._motorcad_adapter = self.system_service.adapter
        self._runtime_diag_dir = container.diagnostics.session_dir
        self._write_runtime_diagnostic = container.diagnostics.write
        self._plugin_release_summary = self.release_service.plugin_summary
        self._release_manifest_payload = self.release_service.manifest
        self._runtime_environment_manifest = self.system_service.environment_manifest
        self._deep_preflight_payload = self.system_service.deep_preflight_payload
        self._motorcad_preflight = self.system_service.motorcad_preflight
        self._task_submission_lock = threading.RLock()
        self._model_runtime_check_lock = threading.RLock()
        self._model_runtime_check_cache: dict[str, dict[str, Any]] = {}
        self._model_runtime_check_inflight: dict[str, threading.Event] = {}
        self._MODEL_RUNTIME_CHECK_CACHE_TTL_S = 300.0
        self._MODEL_RUNTIME_CHECK_CACHE_MAX = 64
        self._analysis_precheck_evidence_lock = threading.RLock()
        self._analysis_precheck_evidence: dict[str, dict[str, Any]] = {}
        self._ANALYSIS_PRECHECK_EVIDENCE_TTL_S = 900.0
        self._ANALYSIS_PRECHECK_EVIDENCE_MAX = 128
        self._analysis_precheck_jobs_lock = threading.RLock()
        self._analysis_precheck_jobs: dict[str, dict[str, Any]] = {}
        self._analysis_precheck_jobs_by_key: dict[str, str] = {}
        self._ANALYSIS_PRECHECK_JOB_TTL_S = 900.0
        self._ANALYSIS_PRECHECK_JOB_MAX = 64
        self._ANALYSIS_PRECHECK_JOB_MAX_RUNTIME_S = 300.0
        self.tasks.native_qualification_resolver = self._native_closure_template_status
        self.result_viewer.native_qualification_resolver = self._native_closure_template_status
        self.results_optimization.native_qualification_resolver = self._native_closure_template_status
        self.engineering_platform.native_qualification_resolver = self._native_closure_template_status
        self.candidate_validation.native_qualification_resolver = self._native_closure_template_status
