/* V0.66 Material assignment renderer. Template material defaults are visible and directly replaceable in Draft mode. */
(() => {
  // Legacy source-contract wording retained for non-visual compatibility: Native 回读.
  const U=window.MCSDesignRenderUtils;if(!U)throw new Error('MCSDesignRenderUtils must load before material renderer');
  const {safe,viewData,authorityStrip,tr,topologyLabel}=U;
  const MATERIAL_COMPONENTS_V062=[
    {key:'Stator Lamination',label:'定子铁心',en:'Stator lamination',type:'Steel'},
    {key:'Rotor Lamination',label:'转子铁心',en:'Rotor lamination',type:'Steel'},
    {key:'Magnet',label:'永磁体',en:'Magnet',type:'Magnet'},
    {key:'Conductor',aliases:['Winding'],label:'绕组导体',en:'Winding conductor',type:'General'},
    {key:'Shaft',label:'转轴',en:'Shaft',type:'Steel'},
    {key:'Housing',label:'机壳',en:'Housing',type:'General'},
    {key:'Sleeve',label:'转子套筒',en:'Rotor sleeve',type:'General'},
  ];
  function materialDisplayName(value){if(value===null||value===undefined||value==='')return tr('沿用 Motor-CAD 模型基线','Use Motor-CAD model baseline');if(typeof value!=='object')return String(value);return value.label||value.name||value.material||value.motorcad_name||tr('已配置材料','Configured material')}
  function valueFor(components,row){if(components[row.key]!==undefined)return components[row.key];for(const alias of row.aliases||[])if(components[alias]!==undefined)return components[alias];return undefined}
  function originFor(provenance,row){if(provenance[row.key])return provenance[row.key];for(const alias of row.aliases||[])if(provenance[alias])return provenance[alias];return{}}
  function materialsView(ctx){
    const {data,editable,motorObject}=viewData(ctx),objectMaterials=motorObject?.materials||{},materials=data.materials||objectMaterials||{},objectComponents=Object.fromEntries(Object.entries(objectMaterials.components||{}).map(([key,value])=>[key,value?.material_name||value?.material||value])),components=materials.component_materials||materials.components||objectComponents||{},provenance=materials.material_provenance||{},inherited=materials.inherited_component_materials||{};
    const known=new Set(MATERIAL_COMPONENTS_V062.flatMap(row=>[row.key,...(row.aliases||[])]));
    const defs=[...MATERIAL_COMPONENTS_V062,...Object.keys(components).filter(key=>!known.has(key)).map(key=>({key,label:key,en:key,type:''}))];
    const assigned=defs.filter(row=>valueFor(components,row)!==undefined&&valueFor(components,row)!==null&&valueFor(components,row)!=='').length;
    const inheritedCount=defs.filter(row=>{const origin=originFor(provenance,row),inheritedValue=valueFor(inherited,row);return origin.source_kind==='template_mtt'||inheritedValue!==undefined}).length;
    const rows=defs.map(row=>{
      const value=valueFor(components,row),inheritedValue=valueFor(inherited,row),origin=originFor(provenance,row),isNative=origin.source_kind==='motorcad_native_readback',isTemplate=!isNative&&(origin.source_kind==='template_mtt'||inheritedValue!==undefined),source=isNative?tr('Motor-CAD 模型回读','Motor-CAD model readback'):origin.source_database_path||origin.source_database||origin.source_template_id||(isTemplate?tr('模板材料','Template material'):tr('Motor-CAD / 电机版本','Motor-CAD / motor revision')),sectionHash=origin.material_section_hash||'';
      return`<tr><td><b>${safe(tr(row.label,row.en||row.key))}</b></td><td><strong>${safe(materialDisplayName(value))}</strong>${isNative?`<small class="material-template-default-v066 native">${tr('原生回读','Native readback')}</small>`:isTemplate?`<small class="material-template-default-v066">${tr('模板默认','Template default')}</small>`:''}</td><td><span title="${safe(source)}">${safe(String(source).split(/[\\/]/).pop()||source)}</span>${sectionHash?`<small title="${safe(sectionHash)}">${tr('材料段','Material section')} ${safe(String(sectionHash).slice(0,12))}…</small>`:''}</td><td>${editable?`<button type="button" class="material-apply-button-v066" data-workbench-material-component="${safe(row.key)}" data-material-type-v062="${safe(row.type)}">${value?tr('选择其他材料','Choose another material'):tr('选择材料','Choose material')}</button>`:`<span class="material-state-v031">${isNative?tr('原生回读','Native readback'):isTemplate?tr('模板基线','Template baseline'):value?tr('版本冻结','Revision snapshot'):tr('模型继承','Model inherited')}</span>`}</td></tr>`;
    }).join('');
    const dbPath=materials.material_database_path||tr('当前模型 / 默认材料数据库','Current model / default material database');
    return`<div class="motorcad-view-v031 materials-view-v031 materials-assignment-v062"><div class="visual-heading-v031"><div><span class="eyebrow">${tr('电机对象 · 材料投影','MOTOR OBJECT · MATERIAL PROJECTION')}</span><h3>${tr('部件材料配置','Component material configuration')}</h3><p>${tr('优先继承模板自身材料定义，通常无需逐项重选。需要替换部件时进入编辑并选择材料。','Template material definitions are inherited by default. Enter edit mode only when a component material must be replaced.')}</p></div><div class="visual-facts-v031"><span>${assigned} ${tr('项已有材料','materials assigned')}</span><span>${inheritedCount} ${tr('项模板默认','template defaults')}</span><span>${safe(topologyLabel(motorObject?.topology_id))}</span></div></div>
      <div class="material-database-toolbar-v0916"><div><b>${tr('Motor-CAD 材料数据库','Motor-CAD material database')}</b><span>${tr('材料列表为空时可自动扫描本机 Solids.mdb / Fluids.mdb，也可进入数据库管理按路径导入。','When the library is empty, Studio can scan local Solids.mdb / Fluids.mdb files or import a database by path.')}</span></div><button type="button" class="primary" data-open-material-library-v061>${tr('材料数据库管理','Material database manager')}</button></div>
      ${editable?`<div class="material-apply-guidance-v066"><b>${tr('应用材料的路径','Material assignment flow')}</b><span>${tr('在部件行选择其他材料，核对关键属性与曲线，再用于当前部件；草稿会自动保存。','Choose another material in a component row, review its properties and curves, then assign it to the component. The draft is saved automatically.')}</span></div>`:`<div class="material-edit-callout-v089g41"><div><b>${tr('当前为只读材料快照','This is a read-only material snapshot')}</b><span>${tr('进入设计草稿后即可逐部件更换材料，并保存为新的电机版本。','Enter the design draft to replace component materials and save a new motor revision.')}</span></div><button type="button" class="primary" data-edit-view-v031="materials">${tr('编辑部件材料','Edit component materials')}</button></div>`}
      <div class="materials-table-v031"><table><thead><tr><th>${tr('电机部件','Motor component')}</th><th>${tr('材料','Material')}</th><th>${tr('数据来源','Data source')}</th><th>${editable?tr('应用','Assign'):tr('状态','Status')}</th></tr></thead><tbody>${rows}</tbody></table></div>
      <div class="materials-meta-v031 materials-library-entry-v061"><div class="materials-meta-copy-v090"><span>${tr('Motor-CAD 材料工程数据库','Motor-CAD engineering material database')}</span><b>${safe(dbPath)}</b><small>${tr('材料库用于检索、曲线和原始属性管理；当前表用于把具体材料绑定到电机版本。','The material library manages search, curves, and source properties; this table binds a selected material to the motor revision.')}</small></div><button type="button" data-open-material-library-v061>${tr('管理材料库 / 查看曲线','Manage material library / view curves')}</button></div>
      <div class="analysis-boundary-v062"><div><b>${tr('冷却介质属于分析工况','Coolant belongs to the analysis operating point')}</b><span>${tr('水 / 油 / 空气、入口温度、流量和对流边界在分析案例中配置，可对同一电机版本建立多个冷却方案。','Water / oil / air, inlet temperature, flow rate, and convection boundaries are configured per analysis case, allowing multiple cooling schemes for the same motor revision.')}</span></div><button type="button" data-design-next-v061="input_data">${tr('进入分析设置 →','Open analysis setup →')}</button></div>${authorityStrip(viewData(ctx).visualSource==='native'?tr('材料来自当前 Motor-CAD 模型回读；此处只读显示','Materials come from the current Motor-CAD model readback; this view is read-only'):tr('当前电机版本的部件材料；保存新版本时一并记录','Component materials of the current motor revision; saved together with a new revision'))}
    </div>`;
  }
  function render(view,ctx){return view==='materials'?materialsView(ctx):null}
  window.MCSDesignMaterials={render,materialsView,MATERIAL_COMPONENTS_V062};
})();
