models:
  i5_Industrial_SPM_Servo_Tooth_Wound:
    preferred: local_mot
    local_mot: data/verified_models/i5_Industrial_SPM_Servo_Tooth_Wound/template.mot
    registered_template: i5
    source_mtt: data/templates/i5_Industrial_SPM_Servo_Tooth_Wound.mtt
  e9_eMobility_IPM:
    preferred: local_mot
    local_mot: data/verified_models/e9_eMobility_IPM/template.mot
    registered_template: e9
    source_mtt: data/templates/e9_eMobility_IPM.mtt
  e14_eMobility_AFM:
    preferred: local_mot
    local_mot: data/verified_models/e14_eMobility_AFM/template.mot
    registered_template: e14
    source_mtt: data/templates/e14_eMobility_AFM.mtt

  a1:
    preferred: local_mot
    local_mot: data/verified_models/a1/template.mot
    registered_template: a1
    source_mtt: data/templates/a1.mtt
