/* V0.22 Motor-CAD parity: continuous model context, parameter impact and solver visualization. */
(() => {
  const impacts={
    pole_count:{title:'极数',component:'转子 / 永磁体',effects:['电频率','极弧与磁极节距','绕组配合','转矩脉动'],hint:'极数变化通常需要同步检查槽极组合与绕组定义。'},
    slot_count:{title:'槽数',component:'定子槽 / 绕组',effects:['槽距','齿宽/槽距','绕组周期','槽满率','绕组因数'],hint:'槽数属于离散拓扑参数；修改后必须重新生成绕组并执行 Motor-CAD 原生检查。'},
    stator_outer_diameter:{title:'定子外径',component:'定子外圆',effects:['轭厚','槽面积','功率密度','热路径'],hint:'外径改变会重分配定子铁心与槽空间。'},
    stator_inner_diameter:{title:'定子内径 / 定子孔径',component:'定子内圆',effects:['气隙圆周','槽深裕量','转子外径','气隙磁密'],hint:'内径与气隙共同决定转子外包络。'},
    air_gap:{title:'气隙',component:'定转子气隙',effects:['气隙磁密','励磁需求','转矩','偏心裕度'],hint:'气隙很敏感，建议小步调整并立即执行几何检查。'},
    tooth_width:{title:'齿宽',component:'定子齿',effects:['齿部磁密','槽面积','槽满率','铁耗'],hint:'增大齿宽会压缩槽面积，可能提高槽满率。'},
    slot_depth:{title:'槽深',component:'定子槽',effects:['槽面积','导体空间','铜耗','轭厚'],hint:'槽深改变会同时影响绕组空间和定子轭厚。'},
    magnet_thickness:{title:'磁体厚度',component:'永磁体',effects:['磁链','反电势','气隙磁密','退磁裕度'],hint:'磁体厚度变化应同时审查电压裕量和磁钢损耗。'},
    magnet_arc_deg:{title:'磁体极弧',component:'永磁体极弧',effects:['气隙磁密波形','齿槽转矩','反电势谐波','转矩脉动'],hint:'极弧影响波形质量，适合结合转矩-角度和气隙磁密曲线评估。'},
    turns_per_coil:{title:'每线圈匝数',component:'绕组',effects:['反电势','电感','铜耗','电压裕量'],hint:'匝数改变后需检查母线电压与槽满率。'},
    parallel_paths:{title:'并联支路',component:'绕组连接',effects:['槽/相/支路整数关系','相电流','铜耗','绕组可制造性'],hint:'并联支路必须满足当前绕组的整数分配约束。'},
    slot_fill_factor:{title:'槽满率',component:'槽内导体',effects:['绕组可制造性','铜耗','热阻'],hint:'Motor-CAD 原生槽满率超过 1.0 时模型无法形成有效绕组。'}
  };

  const impactParts={
    pole_count:['rotor','magnet'],slot_count:['stator-slot'],stator_outer_diameter:['stator'],stator_inner_diameter:['stator','airgap'],air_gap:['airgap'],tooth_width:['stator-slot'],slot_depth:['stator-slot'],magnet_thickness:['magnet'],magnet_arc_deg:['magnet'],turns_per_coil:['stator-slot'],parallel_paths:['stator-slot'],slot_fill_factor:['stator-slot']
  };
  function ensureImpactPanel(anchor,id){if(!anchor)return null;let box=document.getElementById(id);if(box)return box;box=document.createElement('div');box.id=id;box.className='parameter-impact-v022';anchor.insertAdjacentElement('afterend',box);return box}
  function highlightSchematicV022(id){const preview=document.querySelector('#liveDesignPreview');if(!preview)return;preview.querySelectorAll('.parameter-part-active-v022').forEach(x=>x.classList.remove('parameter-part-active-v022'));const parts=impactParts[id]||[];preview.querySelectorAll('[data-schematic-part]').forEach(el=>{const tags=String(el.dataset.schematicPart||'').split(/\s+/);if(parts.some(p=>tags.includes(p)))el.classList.add('parameter-part-active-v022')})}
  function showImpact(id,source){const meta=impacts[id];if(!meta)return;document.querySelectorAll('.parameter-field.focused-v022').forEach(x=>x.classList.remove('focused-v022'));source?.closest('.parameter-field')?.classList.add('focused-v022');highlightSchematicV022(id);const box=ensureImpactPanel(document.querySelector('#liveDesignDimensions'),'taskParameterImpactV022');if(!box)return;box.innerHTML=`<div><span class="eyebrow">参数联动</span><b>${esc(meta.title)} → ${esc(meta.component)}</b></div><p>${esc(meta.hint)}</p><div class="impact-chain-v022">${meta.effects.map((x,i)=>`<span>${i?'→ ':''}${esc(x)}</span>`).join('')}</div>`}
  document.addEventListener('focusin',e=>{const input=e.target.closest('[data-param]');if(!input)return;showImpact(input.dataset.param,input)});
  document.addEventListener('input',e=>{const input=e.target.closest('[data-param]');if(!input)return;showImpact(input.dataset.param,input)});

  const vis={mode:'live',snapshot:null,cases:[],caseRow:null,frame:0,playing:false,raf:0,lastTs:0,liveAngle:0};
  function svgEl(name,attrs={}){const n=document.createElementNS('http://www.w3.org/2000/svg',name);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));return n}
  function stageTone(stage=''){const s=String(stage).toUpperCase();if(s.includes('THERM'))return 'thermal';if(s.includes('EMAG')||s.includes('MAGNET')||s.includes('FEA')||s.includes('SOLV'))return 'emag';if(s.includes('VALID')||s.includes('GEOMET'))return 'validate';return 'idle'}
  function num(value,fallback){const n=Number(value);return Number.isFinite(n)?n:fallback}
  function clamp(value,min,max){return Math.max(min,Math.min(max,value))}
  function polar(cx,cy,r,a){return{x:cx+r*Math.cos(a),y:cy+r*Math.sin(a)}}
  function annularSectorPath(cx,cy,r0,r1,a0,a1){const p0=polar(cx,cy,r1,a0),p1=polar(cx,cy,r1,a1),p2=polar(cx,cy,r0,a1),p3=polar(cx,cy,r0,a0),large=(a1-a0)>Math.PI?1:0;return `M ${p0.x.toFixed(2)} ${p0.y.toFixed(2)} A ${r1} ${r1} 0 ${large} 1 ${p1.x.toFixed(2)} ${p1.y.toFixed(2)} L ${p2.x.toFixed(2)} ${p2.y.toFixed(2)} A ${r0} ${r0} 0 ${large} 0 ${p3.x.toFixed(2)} ${p3.y.toFixed(2)} Z`}
  function addDefs(svg){const defs=svgEl('defs');const marker=svgEl('marker',{id:'feaArrowV022',viewBox:'0 0 10 10',refX:'8',refY:'5',markerWidth:'5',markerHeight:'5',orient:'auto-start-reverse'});marker.appendChild(svgEl('path',{d:'M 0 0 L 10 5 L 0 10 z',class:'fea-arrow-head-v022'}));defs.appendChild(marker);svg.appendChild(defs)}
  function addCaption(svg,lines,x=510,y=70){const t=svgEl('text',{x,y,class:'fea-caption-v022'});lines.forEach((line,i)=>{const span=svgEl('tspan',{x,dy:i?24:0});span.textContent=line;t.appendChild(span)});svg.appendChild(t)}
  function isAxialVisualization(v={}){return Boolean(v.is_axial)||String(v.topology_id||'').toLowerCase()==='afpm'||/AXIAL|AFM|YASA/i.test(String(v.topology||''))}
  function buildRadialMachine(svg,snapshot,angle=0,actual={}){
    const v=snapshot?.visualization||{},slots=Math.max(3,Math.min(72,Math.round(num(v.slot_count,12)))),poles=Math.max(2,Math.min(40,Math.round(num(v.pole_count,8)))),cx=285,cy=195;
    const od=Math.max(1,num(v.stator_outer_diameter_mm,180)),id=clamp(num(v.stator_inner_diameter_mm,od*.63),1,od*.96),rotorDia=clamp(num(v.rotor_diameter_mm,id-num(v.air_gap_mm,1)*2),1,id),shaftDia=clamp(num(v.shaft_diameter_mm,rotorDia*.3),1,rotorDia*.85),outer=142,bore=outer*id/od,rotor=outer*rotorDia/od,shaft=outer*shaftDia/od;
    const stator=svgEl('g',{class:'fea-stator-v022','data-schematic-part':'stator stator-slot'});stator.appendChild(svgEl('circle',{cx,cy,r:outer,class:'fea-stator-ring-v022'}));stator.appendChild(svgEl('circle',{cx,cy,r:bore,class:'fea-stator-bore-v022'}));for(let i=0;i<slots;i++){const a=i*Math.PI*2/slots,x1=cx+(bore+3)*Math.cos(a),y1=cy+(bore+3)*Math.sin(a),x2=cx+(outer-8)*Math.cos(a),y2=cy+(outer-8)*Math.sin(a);stator.appendChild(svgEl('line',{x1,y1,x2,y2,class:'fea-slot-v022'}))}svg.appendChild(stator);
    const field=svgEl('g',{class:`fea-field-v022 ${stageTone(snapshot?.current_stage||v.current_stage)}`});const flux=Number(actual.flux),amp=Number.isFinite(flux)?Math.max(.2,Math.min(1.4,Math.abs(flux))):.78;for(let k=0;k<Math.min(8,poles);k++){const a=(k*Math.PI*2/Math.min(8,poles))+angle*Math.PI/180,r1=Math.max(18,rotor-8),r2=bore+24,side=k%2?1:-1,x1=cx+r1*Math.cos(a),y1=cy+r1*Math.sin(a),x2=cx+r2*Math.cos(a+.20*side),y2=cy+r2*Math.sin(a+.20*side),mx=cx+(r2+35*amp)*Math.cos(a+.11*side),my=cy+(r2+35*amp)*Math.sin(a+.11*side);field.appendChild(svgEl('path',{d:`M ${x1.toFixed(1)} ${y1.toFixed(1)} Q ${mx.toFixed(1)} ${my.toFixed(1)} ${x2.toFixed(1)} ${y2.toFixed(1)}`,class:'fea-flux-v022','marker-end':'url(#feaArrowV022)'}))}svg.appendChild(field);
    const rotorG=svgEl('g',{class:'fea-rotor-v022',transform:`rotate(${angle.toFixed(2)} ${cx} ${cy})`,'data-schematic-part':'rotor magnet'});rotorG.appendChild(svgEl('circle',{cx,cy,r:rotor,class:'fea-rotor-body-v022'}));const rr=Math.max(shaft+13,rotor*.78),magL=Math.max(12,Math.min(28,Math.PI*2*rr/poles*.52));for(let i=0;i<poles;i++){const a=i*Math.PI*2/poles,x=cx+rr*Math.cos(a),y=cy+rr*Math.sin(a);rotorG.appendChild(svgEl('rect',{x:x-magL/2,y:y-5,width:magL,height:10,rx:3,transform:`rotate(${a*180/Math.PI+90} ${x} ${y})`,class:i%2?'fea-magnet-b-v022':'fea-magnet-a-v022'}))}rotorG.appendChild(svgEl('circle',{cx,cy,r:shaft,class:'fea-shaft-v022'}));rotorG.appendChild(svgEl('line',{x1:cx,y1:cy,x2:cx+Math.max(30,rotor*.82),y2:cy,class:'fea-rotor-index-v022'}));svg.appendChild(rotorG);
    return{poles,slots,captionX:500,captionY:65,lines:[`Case ${v.case_id||'-'}`,`${poles} 极 / ${slots} 槽`,`OD ${od.toFixed(1)} · ID ${id.toFixed(1)} mm`]};
  }
  function buildAxialMachine(svg,snapshot,angle=0,actual={}){
    const v=snapshot?.visualization||{},slots=Math.max(3,Math.min(72,Math.round(num(v.slot_count,12)))),poles=Math.max(2,Math.min(40,Math.round(num(v.pole_count,10)))),cx=245,cy=195,outer=142;
    const od=Math.max(1,num(v.axial_rotor_diameter_mm,num(v.stator_outer_diameter_mm,204))),statorOd=Math.max(1,num(v.stator_outer_diameter_mm,od)),id=clamp(num(v.stator_inner_diameter_mm,statorOd*.647),1,statorOd*.94),shaftDia=clamp(num(v.shaft_diameter_mm,id*.76),1,id*.92),inner=clamp(outer*id/statorOd,46,outer-32),shaft=clamp(outer*shaftDia/statorOd,18,inner-8);
    // Face view: annular yokeless stator plus one rotating PM disc projection. This
    // uses the exact Case pole/slot counts and diameters instead of a radial-motor cartoon.
    const rotorDisc=svgEl('g',{class:'fea-axial-disc-v0917','data-schematic-part':'rotor'});rotorDisc.appendChild(svgEl('circle',{cx,cy,r:outer,class:'fea-axial-rotor-ring-v0917'}));rotorDisc.appendChild(svgEl('circle',{cx,cy,r:inner-9,class:'fea-axial-disc-bore-v0917'}));svg.appendChild(rotorDisc);
    const stator=svgEl('g',{class:'fea-stator-v022','data-schematic-part':'stator stator-slot'});stator.appendChild(svgEl('circle',{cx,cy,r:outer-7,class:'fea-axial-stator-ring-v0917'}));stator.appendChild(svgEl('circle',{cx,cy,r:inner,class:'fea-stator-bore-v022'}));for(let i=0;i<slots;i++){const a=i*Math.PI*2/slots,p0=polar(cx,cy,inner+3,a),p1=polar(cx,cy,outer-13,a);stator.appendChild(svgEl('line',{x1:p0.x,y1:p0.y,x2:p1.x,y2:p1.y,class:'fea-slot-v022'}))}svg.appendChild(stator);
    const rotorG=svgEl('g',{class:'fea-rotor-v022',transform:`rotate(${angle.toFixed(2)} ${cx} ${cy})`,'data-schematic-part':'rotor magnet'});const pitch=Math.PI*2/poles,arcRatio=clamp(num(v.magnet_arc_deg,140)/180,.42,.90),magR0=inner+12,magR1=outer-20;for(let i=0;i<poles;i++){const mid=-Math.PI/2+i*pitch,a0=mid-pitch*arcRatio/2,a1=mid+pitch*arcRatio/2;rotorG.appendChild(svgEl('path',{d:annularSectorPath(cx,cy,magR0,magR1,a0,a1),class:i%2?'fea-magnet-b-v022':'fea-magnet-a-v022'}))}rotorG.appendChild(svgEl('circle',{cx,cy,r:shaft,class:'fea-shaft-v022'}));rotorG.appendChild(svgEl('line',{x1:cx,y1:cy,x2:cx+Math.max(28,inner-6),y2:cy,class:'fea-rotor-index-v022'}));svg.appendChild(rotorG);
    // Axial stack section: rotor / magnets / gap / stator / gap / magnets / rotor.
    const sx=455,sy=185,w=215;const statorT=clamp(num(v.stator_lamination_length_mm,35)*1.05,32,70),rotorT=clamp(num(v.rotor_lamination_length_mm,10)*1.25,11,27),magT=clamp(num(v.magnet_thickness_mm,30)*.55,9,24),gap=clamp(num(v.air_gap_mm,1.5)*5,5,12),total=rotorT+magT+gap+statorT+gap+magT+rotorT,startY=sy+(205-total)/2;let y=startY;
    const layer=(height,cls,label)=>{const r=svgEl('rect',{x:sx,y,width:w,height,rx:3,class:cls});r.setAttribute('data-schematic-part',/magnet/.test(cls)?'magnet':/stator/.test(cls)?'stator':'rotor');svg.appendChild(r);if(label){const t=svgEl('text',{x:sx+w/2,y:y+height/2+4,'text-anchor':'middle',class:'fea-stack-label-v0917'});t.textContent=label;svg.appendChild(t)}y+=height};
    layer(rotorT,'fea-stack-rotor-v0917','转子盘');layer(magT,'fea-stack-magnet-v0917','永磁体');layer(gap,'fea-stack-gap-v0917','');layer(statorT,'fea-stack-stator-v0917','单定子');layer(gap,'fea-stack-gap-v0917','');layer(magT,'fea-stack-magnet-v0917','永磁体');layer(rotorT,'fea-stack-rotor-v0917','转子盘');
    const field=svgEl('g',{class:`fea-field-v022 ${stageTone(snapshot?.current_stage||v.current_stage)}`});for(let k=0;k<4;k++){const x=sx+25+k*52,down=k%2===0;field.appendChild(svgEl('path',{d:down?`M ${x} ${startY+rotorT+3} L ${x} ${startY+total-rotorT-3}`:`M ${x} ${startY+total-rotorT-3} L ${x} ${startY+rotorT+3}`,class:'fea-flux-v022','marker-end':'url(#feaArrowV022)'}))}svg.appendChild(field);
    const top=svgEl('text',{x:sx,y:42,class:'fea-view-label-v0917'});top.textContent=v.template_id==='e14_eMobility_AFM'?'AFPM · 双转子单定子':'AFPM · 轴向磁通';svg.appendChild(top);const dim=svgEl('text',{x:sx,y:63,class:'fea-view-dim-v0917'});dim.textContent=`盘径 ${od.toFixed(1)} mm · 单侧气隙 ${num(v.air_gap_mm,1.5).toFixed(2)} mm`;svg.appendChild(dim);
    return{poles,slots,captionX:455,captionY:82,lines:[`Case ${v.case_id||'-'}`,`${poles} 极 / ${slots} 槽`]};
  }
  function buildMachine(svg,snapshot,angle=0,actual={}){
    svg.replaceChildren();addDefs(svg);const v=snapshot?.visualization||{},axial=isAxialVisualization(v),meta=axial?buildAxialMachine(svg,snapshot,angle,actual):buildRadialMachine(svg,snapshot,angle,actual);const stage=String(snapshot?.current_stage||v.current_stage||snapshot?.status||'等待').replaceAll('_',' '),lines=[...meta.lines,stage];if(Number.isFinite(Number(actual.torque)))lines.push(`转矩 ${Number(actual.torque).toFixed(3)} Nm`);if(Number.isFinite(Number(actual.flux)))lines.push(`气隙磁密 ${Number(actual.flux).toFixed(3)} T`);addCaption(svg,lines,meta.captionX,meta.captionY)
  }
  function resultSeries(){const row=vis.caseRow;if(!row)return{};return row.result?.series||row.result_json?.series||{}}
  function seriesPoint(series,index){if(!series?.x?.length||!series?.y?.length)return null;const i=Math.max(0,Math.min(series.x.length-1,index));return{x:Number(series.x[i]),y:Number(series.y[i]),i}}
  function maxFrames(){const s=resultSeries(),a=s.torque_angle_curve?.x?.length||0,b=s.airgap_flux_density_curve?.x?.length||0;return Math.max(a,b,0)}
  function renderResultFrame(){const svg=$('#solverAnimationV022');if(!svg)return;const s=resultSeries(),n=maxFrames(),slider=$('#solverPlaybackSliderV022');if(!n){buildMachine(svg,vis.snapshot,0,{});$('#solverVisualLegendV022').innerHTML='<span class="badge warn">当前 Case 尚无可回放曲线</span><span>请在输出配置中保留“转矩-角度曲线”和“气隙磁密-机械角曲线”。</span>';return}vis.frame=Math.max(0,Math.min(n-1,vis.frame));if(slider){slider.max=String(n-1);slider.value=String(vis.frame)}const tp=seriesPoint(s.torque_angle_curve,Math.round(vis.frame*Math.max(0,(s.torque_angle_curve?.x?.length||1)-1)/Math.max(1,n-1))),bp=seriesPoint(s.airgap_flux_density_curve,Math.round(vis.frame*Math.max(0,(s.airgap_flux_density_curve?.x?.length||1)-1)/Math.max(1,n-1)));const angle=Number.isFinite(tp?.x)?tp.x:Number.isFinite(bp?.x)?bp.x:(vis.frame/n*360);buildMachine(svg,vis.snapshot,angle,{torque:tp?.y,flux:bp?.y});$('#solverVisualLegendV022').innerHTML=`<span class="badge ok">Motor-CAD 结果驱动回放</span><span>角度 ${Number(angle).toFixed(1)}°${Number.isFinite(tp?.y)?` · 转矩 ${tp.y.toFixed(3)} Nm`:''}${Number.isFinite(bp?.y)?` · Bgap ${bp.y.toFixed(3)} T`:''}</span>`;if($('#solverPlaybackStepV022'))$('#solverPlaybackStepV022').textContent=`${vis.frame+1} / ${n}`}
  function renderLive(){const svg=$('#solverAnimationV022');if(!svg||!vis.snapshot)return;buildMachine(svg,vis.snapshot,vis.liveAngle,{});const v=vis.snapshot.visualization||{},tone=stageTone(vis.snapshot.current_stage||v.current_stage),geometryNote=isAxialVisualization(v)?'当前为 AFPM：主视图按盘式极/槽几何绘制，右侧显示双转子-单定子轴向堆叠。':'几何按当前径向电机 Case 参数绘制。';$('#solverVisualLegendV022').innerHTML=`<span class="badge ${tone==='thermal'?'warn':tone==='emag'?'ok':''}">${esc((vis.snapshot.current_stage||v.current_stage||vis.snapshot.status||'等待').replaceAll('_',' '))}</span><span>${geometryNote} 动态场线仅表达求解阶段与转子运动，不作为有限元场值证据。</span>`}
  function renderMetrics(){const box=$('#solverVisualMetricsV022');if(!box)return;const s=vis.snapshot||{},v=s.visualization||{};box.innerHTML=[['Case',v.case_id||'-'],['拓扑',isAxialVisualization(v)?'AFPM':(v.topology||v.topology_id||'-')],['极 / 槽',`${v.pole_count??'-'} / ${v.slot_count??'-'}`],['转速',v.shaft_speed_rpm!=null?`${v.shaft_speed_rpm} rpm`:'-'],['任务进度',`${Math.round((s.progress||0)*100)}%`],['Case状态',v.case_status||'-']].map(([k,val])=>`<div><span>${esc(k)}</span><b>${esc(val)}</b></div>`).join('')}
  function render(){document.querySelectorAll('[data-fea-mode-v022]').forEach(b=>b.classList.toggle('active',b.dataset.feaModeV022===vis.mode));$('#solverPlaybackControlsV022')?.classList.toggle('hidden',vis.mode!=='result');if(vis.mode==='result')renderResultFrame();else renderLive();renderMetrics();const auth=$('#solverVisualAuthorityV022');if(auth)auth.textContent=vis.mode==='result'?'回放角度、转矩和气隙磁密来自当前 Case 的 Motor-CAD Graph/FEA Graph 提取结果。':'实时过程使用真实 Case 几何参数、Task 阶段和进度；场线形态为状态示意，避免将未导出的节点场数据伪装成真实 FEA 云图。'}
  function tick(ts){if(!vis.lastTs)vis.lastTs=ts;const dt=Math.min(80,ts-vis.lastTs);vis.lastTs=ts;if(vis.mode==='live'){const speed=Math.abs(Number(vis.snapshot?.visualization?.shaft_speed_rpm)||600);vis.liveAngle=(vis.liveAngle+dt*Math.max(.008,Math.min(.055,speed/90000)))%360;renderLive()}else if(vis.playing&&maxFrames()>1){vis.frame=(vis.frame+Math.max(1,Math.round(dt/35)))%maxFrames();renderResultFrame()}vis.raf=requestAnimationFrame(tick)}
  function ingestSnapshot(s){vis.snapshot=s;render();if(!vis.raf)vis.raf=requestAnimationFrame(tick)}
  function ingestCases(page){vis.cases=page?.items||[];const preferred=vis.snapshot?.visualization?.case_id;vis.caseRow=vis.cases.find(c=>c.id===preferred&&c.result)||vis.cases.find(c=>['SUCCEEDED','CACHED'].includes(c.execution_status)&&c.result)||vis.cases.find(c=>c.result)||null;if(vis.caseRow&&maxFrames()>0&&['COMPLETED','PARTIALLY_COMPLETED','FAILED'].includes(vis.snapshot?.status)&&vis.mode==='live'){vis.mode='result';render()}else render()}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-fea-mode-v022]');if(b){vis.mode=b.dataset.feaModeV022;vis.playing=false;render()}if(e.target.closest('#solverPlaybackToggleV022')){vis.playing=!vis.playing;e.target.textContent=vis.playing?'暂停':'播放'}});
  document.addEventListener('input',e=>{if(e.target.id==='solverPlaybackSliderV022'){vis.frame=Number(e.target.value)||0;vis.playing=false;if($('#solverPlaybackToggleV022'))$('#solverPlaybackToggleV022').textContent='播放';renderResultFrame()}});
  window.addEventListener('mcs:monitor-cases',e=>ingestCases(e.detail));
  const oldRenderMonitor=renderMonitorSnapshot;renderMonitorSnapshot=function(m){oldRenderMonitor(m);ingestSnapshot(m)};
  window.MCSFEAView={ingestSnapshot,ingestCases,setMode(mode){vis.mode=mode;render()}};

})();
