"""Release manifest and client-capability application service."""
from __future__ import annotations

from pathlib import Path
from typing import Any

from ...module_system import product_module_catalog_report, validate_distribution
from ...release import PRODUCT_VERSION, public_release_manifest


class ReleaseService:
    def __init__(
        self,
        *,
        settings: Any,
        logs: Any,
        module_registry: Any,
        motor_plugins: Any,
        static_dir: Path,
        distribution_manifest_path: Path,
    ) -> None:
        self.settings = settings
        self.logs = logs
        self.module_registry = module_registry
        self.motor_plugins = motor_plugins
        self.static_dir = Path(static_dir)
        self.distribution_manifest_path = Path(distribution_manifest_path)

    def plugin_summary(self) -> dict[str, Any]:
        try:
            catalog = self.motor_plugins.catalog() or {}
        except Exception as exc:
            return {"available": False, "error": f"{type(exc).__name__}: {exc}", "plugins": []}
        plugins = []
        for row in catalog.get("plugins") or []:
            identity = row.get("identity") or {}
            plugins.append({
                "plugin_id": identity.get("plugin_id") or row.get("plugin_id"),
                "plugin_version": identity.get("version") or row.get("plugin_version"),
                "api_version": identity.get("api_version"),
                "minimum_studio_version": identity.get("minimum_studio_version"),
                "maximum_studio_version": identity.get("maximum_studio_version"),
                "contract_hash": row.get("contract_hash"),
            })
        return {
            "available": True,
            "plugin_api_version": catalog.get("plugin_api_version"),
            "plugin_count": len(plugins),
            "plugins": plugins,
        }

    def manifest(self) -> dict[str, Any]:
        payload = public_release_manifest(
            module_report=self.module_registry.validate(),
            effective_motorcad_version=self.settings.motorcad_version,
            plugin_catalog=self.plugin_summary(),
        )
        payload["product_module_catalog"] = product_module_catalog_report()
        payload["distribution_compatibility"] = validate_distribution(
            self.static_dir,
            self.distribution_manifest_path,
        )
        payload["architecture"] = {
            "composition_root": "motorcad_studio.bootstrap.composition_root",
            "application_factory": "motorcad_studio.bootstrap.app_factory",
            "lifecycle": "motorcad_studio.bootstrap.lifecycle",
            "http_operations": "motorcad_studio.api.operations.catalog",
            "control_plane": "motorcad_studio.modules.control_plane",
            "frontend_runtime": "static/core/legacy-runtime.js",
            "binary_field_viewer": "static/features/results/binary-field-viewer.js",
        }
        return payload

    def client_contract(self, *, container_inventory: dict[str, Any] | None = None) -> dict[str, Any]:
        payload = {
            "version": PRODUCT_VERSION, "session_id": self.logs.session_id,
            "release": self.manifest(),
            "module_compatibility": self.module_registry.validate(),
            "features": {
                "release_manifest_v1": True,
                "product_module_catalog_v1": True,
                "fail_closed_distribution_version_gate_v1": True,
                "frontend_module_registry_v1": True,
                "project_trash": True,
                "materials_catalog": True,
                "result_viewer": True,
                "manual_motorcad_exe": True,
                "native_exe_browser": True,
                "geometry_recovery": True,
                "unified_result_viewer": True,
                "geometry_precheck": True,
                "geometry_runtime_check": True,
                "result_case_compare": True,
                "log_boot_sessions": True,
                "project_context": True,
                "motorcad_only_runtime": True,
                "offline_runtime_diagnostics": True,
                "project_first_workflow": True,
                "design_revision_intent": True,
                "scenario_revision_context": True,
                "runtime_submit_gate": True,
                "project_scoped_data_factory": True,
                "startup_runtime_setup": True,
                "project_manager": True,
                "project_edit": True,
                "atomic_template_design_create": True,
                "winding_feasibility_guard": True,
                "native_winding_diagnostics": True,
                "root_cause_ranking": True,
                "self_contained_diagnostic_bundle": True,
                "domain_separated_design_scenario": True,
                "versioned_solver_profiles": True,
                "versioned_output_profiles": True,
                "native_fea_evidence": True,
                "motorcad_session_supervisor": True,
                "motor_model_workbench": True,
                "parameter_dependency_graph": True,
                "native_winding_pattern_evidence": True,
                "immutable_run_configurations": True,
                "run_configuration_replay": True,
                "domain_integrity_audit": True,
                "route_first_page_lifecycle": True,
                "idempotent_task_submission": True,
                "persistent_motorcad_worker_pool": True,
                "validate_and_run_execution_lease": True,
                "atomic_runtime_resource_scheduler": True,
                "worker_capability_handshake": True,
                "runtime_contract_evidence": True,
                "runtime_lifecycle_qualification_v1": True,
                "restartable_runtime_scheduler": True,
                "restartable_persistent_worker_pool": True,
                "sqlite_connection_lifecycle_evidence": True,
                "graceful_runtime_shutdown_recovery": True,
                "memory_admission_control": True,
                "effective_motorcad_exe_binding": True,
                "windows_runtime_contract_campaign": True,
                "runtime_alert_hysteresis": True,
                "revision_preview_effective_snapshot": True,
                "nonlaunching_task_submission_admission": True,
                "task_internal_native_validation_authority": True,
                "persistent_worker_isolated_transport_fallback": True,
                "execution_flow_visualization": True,
                "engineer_facing_ui_guidance": True,
                "single_user_state_model": True,
                "simulation_single_page_engineering_mode": True,
                "human_issue_explanations": True,
                "engineering_result_summary": True,
                "motorcad_visual_dimension_tabs": True,
                "model_first_creation": True,
                "default_model_on_project_entry": False,
                "motor_type_catalog": True,
                "mot_import": True,
                "dynamic_parameter_catalog": True,
                "analysis_definitions": True,
                "multi_analysis_workbench": False,
                "native_fea_event_stream": True,
                "engineering_results_first": True,
                "structured_winding_workspace": True,
                "workflow_state_rail": False,
                "canonical_five_stage_flow": False,
                "engineer_journey_v1": True,
                "design_validate_decide_visible_flow": True,
                "guided_engineer_default_v1": True,
                "guided_advanced_runtime_collapsed_v1": True,
                "golden_motor_design_starters_v1": True,
                "golden_starter_native_qualification_fail_closed": True,
                "engineering_context_store": True,
                "unified_analysis_configuration": True,
                "engineering_lineage_v1": True,
                "engineering_lineage_etag_cache": True,
                "result_context_convergence": True,
                "result_bundle_first_url": True,
                "result_bundle_aggregate_v1": True,
                "result_bundle_item_api": True,
                "result_bundle_aggregate_batch": True,
                "result_set_aggregate_v1": True,
                "comparison_aggregate_v1": True,
                "comparison_metric_unit_gate": True,
                "heavy_result_data_gateway_v1": True,
                "chunk_native_result_data_gateway_v2": True,
                "optimization_result_authority_closure_v1": True,
                "optimization_evidence_ledger_v1": True,
                "optimization_evidence_hash_chain": True,
                "optimization_replay_plan_v1": True,
                "optimization_replay_validation_rerun": True,
                "result_data_content_addressed_storage": True,
                "result_data_chunkpack_v1": True,
                "result_data_chunk_random_access": True,
                "result_data_lazy_loading": True,
                "result_data_etag_windowing": True,
                "solution_service_v1": True,
                "solution_database_vocabulary_v1": True,
                "database_vocabulary_status": True,
                "windows_fullstack_e2e": True,
                "legacy_analysis_implementation_loaded": False,
                "browser_state_machine_e2e": True,
                "latest_only_frontend_boot": True,
                "stable_runtime_ownership": True,
                "engineering_workflow_cockpit": True,
                "unified_run_center": True,
                "run_recovery_failure_center": True,
                "analysis_hmi_common_advanced": True,
                "analysis_templates_v1": True,
                "analysis_smart_defaults_v1": True,
                "analysis_autofix_revision_write_v1": True,
                "optimization_wizard": True,
                "result_engineering_interpretation": True,
                "project_baseline_reference_v1": True,
                "comparability_fingerprint_v1": True,
                "semantic_cross_revision_comparison": True,
                "engineering_interpretation_v1": True,
                "baseline_first_results_ux": True,
                "engineering_requirement_set_v1": True,
                "requirement_evaluation_v1": True,
                "decision_policy_authority_v1": True,
                "requirement_aware_result_interpretation": True,
                "requirement_aware_optimization_guidance": True,
                "requirement_guarded_candidate_promotion": True,
                "qualification_evidence_coverage_v1": True,
                "qualification_campaign_v1": True,
                "adaptive_experiment_plan_proposal_v1": True,
                "requirement_aware_qualification_campaign": True,
                "manufacturing_tolerance_set_v1": True,
                "manufacturing_probabilistic_qualification_v1": True,
                "canonical_unit_registry_v1": True,
                "requirement_aware_multi_fidelity_active_learning_v1": True,
                "low_fidelity_formal_qualification": False,
                "decision_first_results_cockpit_v1": True,
                "optimization_guidance_v1": True,
                "optimization_decision_timeline_v1": True,
                "windows_motorcad_fullflow_acceptance_v1": True,
                "windows_motorcad_production_qualification_v2": True,
                "windows_production_qualification_matrix": True,
                "windows_native_golden_journey_qualification": True,
                "windows_native_golden_journey_matrix": True,
                "native_semantic_binding_authority": True,
                "native_geometry_winding_readback_authority": True,
                "native_validation_fault_tree_repair_authority": True,
                "editor_transaction_native_reconciliation": True,
                "native_preview_visualization_reconciliation": True,
                "native_spatial_geometry_result_overlay_authority": True,
                "production_soak_qualification_v1": True,
                "production_soak_matrix": True,
                "ui_soak_recovery_fault_qualification": True,
                "ui_soak_matrix": True,
                "ui_fault_injection_matrix": True,
                "engineer_ux_convergence": True,
                "release_candidate_gate": True,
                "rc_human_acceptance_checklist": True,
                "static_asset_unique_load_gate": True,
                "global_shell_typography_copy_convergence": True,
                "guided_copy_audit": True,
                "shell_responsive_layout_gate": True,
                "production_hardening_runtime_telemetry_v1": True,
                "workstation_acceptance_fail_closed": True,
                "thermal_topology_view": True,
                "native_fea_display_controls": True,
                "structured_winding_definition_evidence": True,
                "thermal_network_evidence_contract": True,
                "native_fea_multistep_probe": True,
                "engineering_decision_compare_v2": True,
                "recipe_schema_v3": True,
                "capability_evidence_ladder": True,
                "motorcad_context_navigation": True,
                "dedicated_analysis_editors": True,
                "result_contract_completeness": True,
                "physical_cooling_flow_circuit": True,
                "sensitivity_case_estimator": True,
                "visual_automation_wrapper": True,
                "native_fea_contract_gate": True,
                "automatic_result_extraction": True,
                "batch_fea_completeness_summary": True,
                "multi_scenario_case_execution": True,
                "strict_legacy_result_contract_gate": True,
                "actual_case_stage_visualization": True,
                "global_fea_field_range": True,
                "native_fea_region_filter": True,
                "native_fea_nearest_point_probe": True,
                "quality_aware_project_guidance": True,
                "usable_result_autoselection": True,
                "safe_task_control_actions": True,
                "terminal_monitor_handoff": True,
                "unsaved_parameter_guard": True,
                "execution_plan_v2": True,
                "result_bundle_v1": True,
                "typed_engineering_results": True,
                "result_bundle_execution_plan_provenance": True,
                "result_bundle_native_qualification_provenance": True,
                "legacy_solver_result_compatibility_projection": True,
                "robust_optimization_object_layer": True,
                "uncertainty_scenario_set_v1": True,
                "robust_candidate_evaluation_v1": True,
                "constraint_margin_analysis": True,
                "sensitivity_study_v1": True,
                "sensitivity_local": True,
                "sensitivity_morris": True,
                "sensitivity_sobol_full_factorial": True,
            },
        }
        payload["features"].update({
            "service_container_v1": True,
            "composition_root_v1": True,
            "application_lifecycle_coordinator_v1": True,
            "platform_release_router_v1": True,
            "platform_system_router_v1": True,
            "platform_observability_router_v1": True,
            "bounded_http_operation_catalog_v1": True,
            "compatibility_route_count_zero_v1": True,
            "control_plane_commands_v1": True,
            "transactional_outbox_v1": True,
            "qualification_evidence_chain_v1": True,
            "native_runtime_fencing_v1": True,
            "requirements_revision_v1": True,
            "binary_field_data_v1": True,
            "indexed_webgl2_field_viewer_v1": True,
            "sealed_frontend_runtime_capsule_v1": True,
            "frontend_single_entry_v1": True,
            "consolidated_stylesheet_v1": True,
            "one_click_launcher_v1": True,
        })
        payload["architecture"] = {
            "composition_root": "motorcad_studio.bootstrap.composition_root",
            "application_factory": "motorcad_studio.bootstrap.app_factory",
            "lifecycle": "motorcad_studio.bootstrap.lifecycle",
            "platform_routers": ["release", "system", "observability"],
            "domain_compatibility": {"enabled": False, "operation_count": 0},
            "http_operations": "motorcad_studio.api.operations.catalog",
            "frontend_runtime": "sealed-capsule-plus-es-modules",
            "container": container_inventory or {},
        }
        return payload


__all__ = ["ReleaseService"]
